export const PostedCardData = [
    {
        PostedImage: require('../Img/PostedImage/Penguin.jpg'),
        ArtistPf: require('../Img/UserImg/skull_fp.png'),
        ArtName: 'Penguin',
        ArtistName: 'DaVoidC',
        Price: '309',
        Likes: '3',
        Comments: '10000',
        postId: '0',
        tags: ['animal', 'cute'],
        ArtistHandle: 'mario',
        commission: '1',
    },
    {
        PostedImage: require('../Img/PostedImage/bgsky.png'),
        ArtistPf: require('../Img/UserImg/skull_fp.png'),
        ArtName: 'Penguin',
        ArtistName: 'DaVoidC',
        Price: '0',
        Likes: '10500',
        Comments: '1500',
        postId: '1',
        tags: ['nature', 'landscape'],
        ArtistHandle: 'david',
        commission: '0',
    },
    {
        PostedImage: require('../Img/PostedImage/FrogTurtle.webp'),
        ArtistPf: require('../Img/UserImg/skull_fp.png'),
        ArtName: 'FrogTurtle',
        ArtistName: 'DaVoidC',
        Price: '0',
        Likes: '12000',
        Comments: '1200',
        postId: '2',
        tags: [
            'animal',
            'fantasy',
            'nature',
            'landscape',
            'cute',
            'fantasy',
            'nature',
            'landscape',
            'cute',
        ],
        ArtistHandle: 'piasco',
        commission: '0',
    },
    {
        PostedImage: require('../Img/PostedImage/Giraffe.webp'),
        ArtistPf: require('../Img/UserImg/skull_fp.png'),
        ArtName: 'Giraffe',
        ArtistName: 'DaVoidC',
        Price: '999',
        Likes: '17000',
        Comments: '1000',
        postId: '3',
        tags: ['animal', 'nature'],
        ArtistHandle: 'animal',
        commission: '1',
    },
    {
        PostedImage: require('../Img/PostedImage/SnakeBear.webp'),
        ArtistPf: require('../Img/UserImg/skull_fp.png'),
        ArtName: 'Penguin',
        ArtistName: 'DaVoidC',
        Price: '599',
        Likes: '105000',
        Comments: '500',
        postId: '4',
        tags: ['animal', 'fantasy'],
        ArtistHandle: 'mario',
        commission: '1',
    },
]
